### ISSUE TITLE
Clickhouse backend reads HDFS file exception

### ISSUE THREAD

**Issue by ASiegeLion** [apache/incubator-gluten#7285]
### Backend

CH (ClickHouse)

### Bug description

2024-09-20T10:21:35.670057896+08:00 20. Java_org_apache_gluten_vectorized_BatchIterator_nativeHasNext @ 0x0000000005e765d7

2024-09-20T10:21:35.670060237+08:00 

2024-09-20T10:21:35.670062920+08:00 	at org.apache.gluten.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:39)

2024-09-20T10:21:35.670065532+08:00 	at org.apache.gluten.backendsapi.clickhouse.CollectMetricIterator.hasNext(CHIteratorApi.scala:332)

2024-09-20T10:21:35.670068131+08:00 	at org.apache.gluten.vectorized.CloseableCHColumnBatchIterator.$anonfun$hasNext$1(CloseableCHColumnBatchIterator.scala:42)

2024-09-20T10:21:35.670070518+08:00 	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)

2024-09-20T10:21:35.670073013+08:00 	at org.apache.gluten.metrics.GlutenTimeMetric$.withNanoTime(GlutenTimeMetric.scala:41)

2024-09-20T10:21:35.670075814+08:00 	at org.apache.gluten.vectorized.CloseableCHColumnBatchIterator.hasNext(CloseableCHColumnBatchIterator.scala:42)

2024-09-20T10:21:35.670078261+08:00 	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)

2024-09-20T10:21:35.670080648+08:00 	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)

2024-09-20T10:21:35.670083225+08:00 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)

2024-09-20T10:21:35.670096914+08:00 	at org.apache.spark.util.random.SamplingUtils$.reservoirSampleAndCount(SamplingUtils.scala:41)

2024-09-20T10:21:35.670105585+08:00 	at org.apache.spark.RangePartitioner$.$anonfun$sketch$1(Partitioner.scala:306)

2024-09-20T10:21:35.670113927+08:00 	at org.apache.spark.RangePartitioner$.$anonfun$sketch$1$adapted(Partitioner.scala:304)

2024-09-20T10:21:35.670116839+08:00 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2(RDD.scala:915)

2024-09-20T10:21:35.670119327+08:00 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2$adapted(RDD.scala:915)

2024-09-20T10:21:35.670122000+08:00 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)

2024-09-20T10:21:35.670124902+08:00 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)

2024-09-20T10:21:35.670127818+08:00 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)

2024-09-20T10:21:35.670130570+08:00 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)

2024-09-20T10:21:35.670133342+08:00 	at org.apache.spark.scheduler.Task.run(Task.scala:131)

2024-09-20T10:21:35.670135847+08:00 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)

2024-09-20T10:21:35.670138536+08:00 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)

2024-09-20T10:21:35.670141095+08:00 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)

2024-09-20T10:21:35.670144107+08:00 	... 3 more

2024-09-20T10:21:35.670150461+08:00 Caused by: org.apache.gluten.exception.GlutenException: Unable to connect to HDFS: HdfsRpcException: RPC channel to "fs-hiido-yycluster01-yynn1.hiido.host.int.yy.com:38020" got protocol mismatch: RPC channel cannot find pending call: id = -33.: While executing SubstraitFileSource
[spark-kubernetes-driver.log](https://github.com/user-attachments/files/17069045/spark-kubernetes-driver.log)

### Spark version

None

**Comment by ASiegeLion** [comment]
gluten conf:
![image](https://github.com/user-attachments/assets/c32714dc-428e-47cc-a325-721ca7cb9061)

**Comment by yhcast0** [comment]
Got the same problem and solved by making a change to hadoop server side config `hadoop.rpc.protection` from `authentication,privacy` to `authentication` (my hadoop is HDP 3.1.0)
![img_v3_02fh_ef3ecb88-ffd3-4651-89cc-f0dcfb153dag](https://github.com/user-attachments/assets/59b12d64-6c44-439b-8f34-f6dfa61933aa)
The root cause is not clear to me, hope someone can explain this, thanks.

**Comment by ASiegeLion** [comment]
> Got the same problem and solved by making a change to hadoop server side config `hadoop.rpc.protection` from `authentication,privacy` to `authentication` (my hadoop is HDP 3.1.0) ![img_v3_02fh_ef3ecb88-ffd3-4651-89cc-f0dcfb153dag](https://private-user-images.githubusercontent.com/39019287/375445354-59b12d64-6c44-439b-8f34-f6dfa61933aa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTk5NjQsIm5iZiI6MTcyODY5OTY2NCwicGF0aCI6Ii8zOTAxOTI4Ny8zNzU0NDUzNTQtNTliMTJkNjQtNmM0NC00MzliLThmMzQtZjZkZmE2MTkzM2FhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDAyMjEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMTFlNDQ3ODVhYjQxZDc5OWQ5Y2U3OTgwOTBlMzBlZmY4ODVkNzZjYTNlZDMyYTg1NWU4YmE3N2E3YTYzNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j40HJoRGrNA3FJh5k4cN-W_nuUrXdHrw_WaJgw565UY) Looks like disabling of data encryption helps. The root cause is not clear to me, hope someone can explain, thanks.

we modify the configuration
![image](https://github.com/user-attachments/assets/e9501743-ca3f-4a26-b281-5538da4ec7ba)
but the exception still exists
![264fb2cdbf60055ae2cfd7ad64c18e3](https://github.com/user-attachments/assets/4744f1a0-4bde-4715-8612-0468adaa7cba)
[spark-kubernetes-executor.log](https://github.com/user-attachments/files/17348527/spark-kubernetes-executor.log)
